name: F1 Firmware

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
    
    - uses: carlosperate/arm-none-eabi-gcc-action@v1.5.2
    - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain

      run: git submodule update --init --recursive
    - name: install toolchain

    - name: check toolchain
      run: arm-none-eabi-gcc --version
    - name: make
      run: make BOARD=NAZE -j4 -l4
